[package]
authors = ["Christian <chriamue@gmail.com>"]
description = "oidc provider using web3 technologies"
edition = "2021"
license = "MIT"
name = "web3-login"
readme = "README.md"
repository = "https://github.com/web3-login/web3-login"
version = "0.1.0"

[features]
default = ["account"]
account = ["web3"]
nft = ["account"]

[dependencies]
chrono = "0.4"
hex = "0.4"
openidconnect = "2.2"
rocket = {version = "0.5.0-rc.1", features = ["json"]}
rocket-include-static-resources = {version = "0.10", features = ["cache"]}
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
tokio = {version = "1.17", features = ["full"]}
url = "2.2"
uuid = { version = "0.8", features = ["serde", "v4"] }
web3 = {version = "0.18", default-features = false, features = ["signing", "http-rustls-tls"], optional = true}
