key_id: "changeme"
node_provider:
  default: "https://kovan.infura.io/v3/43"
  kovan: "https://kovan.infura.io/v3/43"
  okt: "https://exchaintestrpc.okex.org"
  clv: "https://rpc-3.clover.finance"
  heco: "https://http-testnet.hecochain.com"
  celo: "https://alfajores-forno.celo-testnet.org"
  polygon: "https://matic-mumbai.chainstacklabs.com/"
  metis: "https://stardust.metis.io/?owner=588"
  meter: "https://rpctest.meter.io/"
  theta: "https://eth-rpc-api-testnet.thetatoken.org/rpc"
  avax: "https://api.avax-test.network/ext/bc/C/rpc"
  binance: "https://data-seed-prebsc-1-s1.binance.org:8545/"
  evmos: "https://ethereum.rpc.evmos.dev"
  main: "https://cloudflare-eth.com"
chain_id:
  default: 42
  kovan: 42
  okt: 65
  clv: 1023
  heco: 256
  celo: 44787
  polygon: 80001
  metis: 588
  meter: 83
  theta: 365
  avax: 43113
  binance: 97
  evmos: 9000
  main: 1
ext_hostname: "https://oidc.web3-login.example.com"
frontend_host: "https://web3-login.example.com"
eddsa_pem: "-----BEGIN PRIVATE KEY-----\nMC4CAQAwBQYDK2VwBCIEIOKlIljKAZAW2V8x4Vq+Xc9k6IVQplhg1nyeoaj245Zp\n-----END PRIVATE KEY-----"
