version: "3.2"
services:
  provider:
    # image: ghcr.io/web3-login/web3-login/web3-login:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config.yml:/config.yml
    # ports:
    #  - "8080:8080"

  tunnel:
      image: cloudflare/cloudflared:2024.1.4
      command: tunnel --config /etc/cloudflared/config.yml --no-autoupdate run
      volumes:
        - "./.cloudflared:/etc/cloudflared"
